### ISSUE TITLE
feature request: Svelte / Vite / RollUp

### ISSUE THREAD

**Issue by cristianvogel** [Smona/faust-loader#4]
Hi! 

I am working with SvelteKit , which uses Vite and RollUp. I'd like to try to use FAUST within a project built on these technologies. Will faust-loader work in this config?

**Comment by Smona** [comment]
Hi Cristian, I'm glad you're getting into faust!

faust-loader is specific to webpack, so it won't work directly with rollup. It looks like there's a [rollup plugin](https://www.npmjs.com/package/@betit/rollup-plugin-webpack-loader) which attempts to support using webpack loaders with rollup, but it's not very popular so who knows how well it works.

You're also welcome to take inspiration from this project to create a faust rollup plugin. You should be able to re-use `FaustAudioProcessorNode.ts` and `loadProcessor.ts`, which are mostly adapted from the faust wasm compiler itself. You would just need to port the logic in `faustLoader.ts` to be compatible with rollup's plugin format.
